Create database blogphp;

use blogphp;

CREATE TABLE User (
    id INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    pseudo VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    mdp VARCHAR(100) NOT NULL,
    admin BOOLEAN DEFAULT false,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    archivedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Post (
    id INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    userId INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    text LONGTEXT,
    imageURL VARCHAR(200),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    archivedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE Comment (
    id INTEGER NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    postId INTEGER NOT NULL,
    userId INTEGER NOT NULL,
    text LONGTEXT NOT NULL,
    valided BOOLEAN DEFAULT false,
    adminId INTEGER NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    archivedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (userId) REFERENCES Users(id),
    FOREIGN KEY (postId) REFERENCES Posts(id),
    FOREIGN KEY (adminId) REFERENCES Users(id)
);